RightForMeCareerVault.initializeCareerVault();
RightForMeResumeController.initializeResumeController();
RightForMeTailoringController.initializeTailoringController();
RightForMeCoverLetterController.initializeCoverLetterController();
RightForMeJobAnalyzer.initializeAnalyzer();
