RightForMeCareerVault.initializeCareerVault();
RightForMeResumeController.initializeResumeController();
RightForMeTailoringController.initializeTailoringController();
RightForMeCoverLetterController.initializeCoverLetterController();
RightForMeApplicationPacketController.initializeApplicationPacketController();
RightForMeJobAnalyzer.initializeAnalyzer();
