RightForMeCareerVault.initializeCareerVault();
RightForMeJobsAppliedController.initializeJobsAppliedController();
RightForMeResumeController.initializeResumeController();
RightForMeTailoringController.initializeTailoringController();
RightForMeCoverLetterController.initializeCoverLetterController();
RightForMeApplicationPacketController.initializeApplicationPacketController();
RightForMeJobAnalyzer.initializeAnalyzer();
